# Generated by Django 4.2.11 on 2024-04-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_TAXIES',
            fields=[
                ('taxino', models.IntegerField(primary_key=True, serialize=False)),
                ('cur_loc', models.CharField(max_length=1)),
                ('drop_time', models.IntegerField()),
                ('short_dis', models.IntegerField()),
                ('prev_loc', models.CharField(max_length=1)),
                ('pick_time', models.IntegerField()),
                ('pick_loc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SCHEDULED_TAXIES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxi_id', models.IntegerField()),
                ('pick_loc', models.CharField(max_length=1)),
                ('drop_loc', models.CharField(max_length=1)),
                ('pick_time', models.IntegerField()),
                ('drop_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TAXI_DETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxino', models.IntegerField()),
                ('pick_loc', models.CharField(max_length=1)),
                ('drop_loc', models.CharField(max_length=1)),
                ('pick_time', models.IntegerField()),
                ('drop_time', models.IntegerField()),
                ('cus_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TAXI_INCOME',
            fields=[
                ('taxino', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
