# Generated by Django 4.2.11 on 2024-04-09 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_taxies',
            name='pick_loc',
            field=models.CharField(max_length=1),
        ),
    ]
